 <article class="product">
    <div class="product-image">
        <img src="{{image}}">
    </div>
    <div class="product-info">
        
            <h1 class="title">{{title}}</h1>
            <p class="description">
               {{description}}<br><br>
               <span>Sizes: {{sizes}}   </span>
            </p>
            
            <p>
                <span class="price">{{price}} €</span>
                <button class="buy-btn">Buy</button>
            </p>
        
    </div>
</article>